// Minimal VLESS proxy — POST /vless as an h2 tunnel. Cert + pin are generated by
// examples/CMakeLists.txt; run from build/examples/.

#include <cstdint>
#include <fstream>
#include <iostream>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

#include <uvent/Uvent.h>

#include <unet/core/config.hpp>
#include <unet/core/streams/plaintext.hpp>
#ifdef _WIN32
#include <unet/core/streams/schannel.hpp>
#else
#include <unet/core/streams/openssl.hpp>
#endif
#include <unet/http.hpp>
#include <unet/http/router/radix.hpp>
#include <unet/http/v1/connection.hpp>
#include <unet/http/v2/connection.hpp>
#include <unet/vless/authentication/memory.hpp>
#include <unet/vless/upgrade.hpp>


namespace {

    std::optional<usub::unet::vless::UUID> uuidFromString(std::string_view s) {
        usub::unet::vless::UUID out{};
        std::size_t byte_idx = 0;
        auto hexNib = [](char c) -> int {
            if (c >= '0' && c <= '9') return c - '0';
            if (c >= 'a' && c <= 'f') return c - 'a' + 10;
            if (c >= 'A' && c <= 'F') return c - 'A' + 10;
            return -1;
        };
        for (std::size_t i = 0; i < s.size();) {
            if (s[i] == '-') {
                ++i;
                continue;
            }
            if (i + 1 >= s.size() || byte_idx >= 16) return std::nullopt;
            const int hi = hexNib(s[i]);
            const int lo = hexNib(s[i + 1]);
            if (hi < 0 || lo < 0) return std::nullopt;
            out[byte_idx++] = static_cast<std::byte>((hi << 4) | lo);
            i += 2;
        }
        return (byte_idx == 16) ? std::optional{out} : std::nullopt;
    }

    std::string readPin() {
        std::ifstream in{"cert.pin"};
        std::string pin;
        in >> pin;
        return pin;
    }

}// namespace


int main() {
    constexpr const char *kUuid = "11111111-1111-1111-1111-111111111111";
    const auto parsed = uuidFromString(kUuid);
    if (!parsed) {
        std::cerr << "invalid UUID literal\n";
        return 1;
    }

    std::vector<usub::unet::vless::User> users{
            {.uuid = *parsed, .email = "demo"},
    };
    auto auth = std::make_shared<usub::unet::vless::MemoryAuthenticationProvider>(users);

    usub::unet::core::Config config;
    {
        usub::unet::core::Config::Object plain_section;
        plain_section.emplace("host", usub::unet::core::Config::Value{std::string{"127.0.0.1"}});
        plain_section.emplace("port", usub::unet::core::Config::Value{static_cast<std::uint64_t>(8080)});

        usub::unet::core::Config::Object tls_section;
        tls_section.emplace("host", usub::unet::core::Config::Value{std::string{"0.0.0.0"}});
        tls_section.emplace("port", usub::unet::core::Config::Value{static_cast<std::uint64_t>(8443)});
#ifdef _WIN32
        tls_section.emplace("pfx",      usub::unet::core::Config::Value{std::string{"server.pfx"}});
        tls_section.emplace("password", usub::unet::core::Config::Value{std::string{"demo"}});
#else
        tls_section.emplace("cert", usub::unet::core::Config::Value{std::string{"cert.pem"}});
        tls_section.emplace("key",  usub::unet::core::Config::Value{std::string{"key.pem"}});
#endif

        usub::unet::core::Config::Object http_section;
        http_section.emplace("PlainTextStream", usub::unet::core::Config::Value{std::move(plain_section)});
#ifdef _WIN32
        http_section.emplace("SChannelStream", usub::unet::core::Config::Value{std::move(tls_section)});
#else
        http_section.emplace("OpenSSLStream", usub::unet::core::Config::Value{std::move(tls_section)});
#endif
        config.root.emplace("HTTP", usub::unet::core::Config::Value{std::move(http_section)});
    }

    usub::Uvent uvent{static_cast<int>(std::max(1u, std::thread::hardware_concurrency()))};

    usub::unet::http::ServerImpl<
            usub::unet::http::router::Radix,
            usub::unet::core::stream::PlainText,
#ifdef _WIN32
            usub::unet::core::stream::SChannelStream<"h2", "http/1.1">
#else
            usub::unet::core::stream::OpenSSLStream<"h2", "http/1.1">
#endif
            >
            server{uvent, config};

    server.onHTTP1Connection([](usub::unet::http::v1::Connection &conn) {
        std::cerr << "[h1] connection from " << conn.peer.ip << ":" << conn.peer.port << " alpn=" << conn.peer.alpn << "\n";
    });
    server.onHTTP2Connection([](usub::unet::http::v2::Connection &conn) {
        std::cerr << "[h2] connection from " << conn.peer.ip << ":" << conn.peer.port << " alpn=" << conn.peer.alpn << "\n";
    });
    server.onHTTP2Stream([](usub::unet::http::v2::Connection &, std::uint32_t sid) {
        std::cerr << "[h2] new stream id=" << sid << "\n";
    });

    server.addMiddleware(usub::unet::http::MIDDLEWARE_PHASE::HEADER,
                         [](usub::unet::http::RequestReader &req,
                            usub::unet::http::ResponseWriter &) -> usub::uvent::task::Awaitable<bool> {
                             std::cerr << "[req] version=" << static_cast<int>(req.metadata.version)
                                       << " method=" << req.metadata.method_token
                                       << " path=" << req.metadata.uri.path << "\n";
                             co_return true;
                         });

    auto vless_upgrade_handler = [auth](usub::unet::http::RequestReader &req,
                                        usub::unet::http::ResponseWriter &res,
                                        usub::unet::http::UpgradeContext &ctx) -> usub::uvent::task::Awaitable<void> {
        std::cerr << "[vless] upgrade handler invoked\n";
        co_await usub::unet::vless::upgrade(req, res, ctx, auth);
        std::cerr << "[vless] upgrade returned, accepted=" << ctx.accepted << "\n";
    };
    server.handleUpgrade("POST", "/vless", vless_upgrade_handler);
    server.handleUpgrade("POST", "/vless/", vless_upgrade_handler);

    const std::string pin = readPin();

    std::cout << "unet VLESS server\n"
                 "  listen : https://127.0.0.1:8443/vless  (POST → h2 tunnel)\n"
                 "  uuid   : "
              << kUuid << "\n"
                 "  pin    : " << (pin.empty() ? "<missing cert.pin — rebuild examples>" : pin) << "\n\n"
                 "Client config (XRay / v2rayN / Happ):\n"
                 "{\n"
                 "  \"log\": { \"loglevel\": \"warning\" },\n"
                 "  \"inbounds\": [\n"
                 "    { \"listen\": \"127.0.0.1\", \"port\": 10808, \"protocol\": \"socks\",\n"
                 "      \"settings\": { \"auth\": \"noauth\", \"udp\": true } }\n"
                 "  ],\n"
                 "  \"outbounds\": [{\n"
                 "    \"tag\": \"proxy\",\n"
                 "    \"protocol\": \"vless\",\n"
                 "    \"settings\": { \"vnext\": [{\n"
                 "      \"address\": \"127.0.0.1\",\n"
                 "      \"port\": 8443,\n"
                 "      \"users\": [{ \"id\": \""
              << kUuid << "\", \"encryption\": \"none\" }]\n"
                 "    }] },\n"
                 "    \"streamSettings\": {\n"
                 "      \"network\": \"xhttp\",\n"
                 "      \"security\": \"tls\",\n"
                 "      \"tlsSettings\": {\n"
                 "        \"serverName\": \"localhost\",\n"
                 "        \"pinnedPeerCertSha256\": \""
              << pin << "\"\n"
                 "      },\n"
                 "      \"xhttpSettings\": {\n"
                 "        \"host\": \"localhost\",\n"
                 "        \"path\": \"/vless\",\n"
                 "        \"mode\": \"stream-one\"\n"
                 "      }\n"
                 "    }\n"
                 "  }]\n"
                 "}\n";

    uvent.run();
    return 0;
}
